/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/alternatives": {
    delete?: never;
    get?: never;
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    /**
     * Alternatives
     * @description Retrieve alternative routes for a specific disruption situation
     */
    post: operations["alternatives_v1_alternatives_post"];
    put?: never;
    trace?: never;
  };
  "/v1/alternatives/by_disruption_communication_id/{disruption_communication_id}": {
    delete?: never;
    /**
     * By Disruption Communication Id
     * @deprecated
     * @description Get alternative routes for a specific disruption communication ID
     *
     *     This is intended for testing and debugging purposes only. The disruption
     *     scenario are the corresponing lines with the disruption interval, sections
     *     to cover are the longest sections list of the corresponing lines.
     */
    get: operations["by_disruption_communication_id_v1_alternatives_by_disruption_communication_id__disruption_communication_id__get"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
  "/v1/disruptions-metadata": {
    delete?: never;
    /**
     * Disruptions Metadata
     * @deprecated
     */
    get: operations["disruptions_metadata_v1_disruptions_metadata_get"];
    head?: never;
    options?: never;
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    patch?: never;
    post?: never;
    put?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  headers: never;
  parameters: never;
  pathItems: never;
  requestBodies: never;
  responses: never;
  schemas: {
    /**
     * AlternativeRoutes
     * @description Alternative routes [alternative Verbindungen] between a start and end applicable for a particular disruption communication [Störungskommunikation].
     */
    "AlternativeRoutes-Input": {
      from: components["schemas"]["StopPlaceEmbedded"];
      /**
       * Replacementtransports
       * @description Replacement transports [Ersatzverkehre] information for a particular disruption-communication.
       */
      replacementTransports: components["schemas"]["ReplacementTransport"][];
      to: components["schemas"]["StopPlaceEmbedded"];
    };
    /**
     * AlternativeRoutes
     * @description Alternative routes [alternative Verbindungen] between a start and end applicable for a particular disruption communication [Störungskommunikation].
     */
    "AlternativeRoutes-Output": {
      from: components["schemas"]["StopPlaceEmbedded"];
      /**
       * Replacementtransports
       * @description Replacement transports [Ersatzverkehre] information for a particular disruption-communication.
       */
      replacementTransports: components["schemas"]["ReplacementTransport"][];
      to: components["schemas"]["StopPlaceEmbedded"];
    };
    /**
     * AlternativeRoutesRequest
     * @description Request body for an alternative routes request.
     */
    AlternativeRoutesRequest: {
      disruptionScenario: components["schemas"]["DisruptionScenario"];
      /**
       * Knownalternativeroutes
       * @description Known alternative routes for the disruption scenario. May be empty.
       */
      knownAlternativeRoutes?: components["schemas"]["AlternativeRoutes-Input"][];
      /** @description The organisational unit the alternative routes are requested for. */
      organisationalUnit?:
        | components["schemas"]["DisruptionCommunicationOrganisationalUnit"]
        | null;
      /** @description Continuous line sections for which alternative routes are requested. */
      sectionsToCover: components["schemas"]["SectionsToCover"];
    };
    /**
     * AlternativeRoutesResponse
     * @description Response to an alternative routes request.
     */
    AlternativeRoutesResponse: {
      /**
       * Additionalinfo
       * @description Unspecified additional information for debugging. Do not use in production code.
       */
      additionalInfo?: {
        [key: string]: unknown;
      } | null;
      /** Annotatedalternativeroutes */
      annotatedAlternativeRoutes: components["schemas"]["AnnotatedAlternativeRoutes"][];
      /** @description Indicate whether alternatives are delivered and the reason if nothing is delivered. */
      status: components["schemas"]["ResponseStatus"];
    };
    /**
     * AnnotatedAlternativeRoutes
     * @description Alternative route collection consisting of one or more legs
     */
    AnnotatedAlternativeRoutes: {
      /**
       * Additionalinfo
       * @description Unspecified additional information for debugging. Do not use in production code.
       */
      additionalInfo?: {
        [key: string]: unknown;
      } | null;
      /**
       * Alternativerouteparts
       * @description List of alternative routes in the RIS-API format.
       */
      alternativeRouteParts: components["schemas"]["AlternativeRoutes-Output"][];
      /**
       * Begin
       * Format: date-time
       */
      begin: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      /**
       * Estimatedtraveltime
       * @description Estimated travel time in seconds for a typical connection of the alternative routes.
       */
      estimatedTravelTime?: null | number;
      /**
       * Headwaydetails
       * @description A list of intervals with corresponding headways.
       */
      headwayDetails?: components["schemas"]["IntervalHeadway"][] | null;
      /**
       * Intervals
       * @description Optional intervals in OSM opening hours format where the alternative is available.
       *
       *     Only the weekday and time features of the 'opening hours' specification is used.
       */
      intervals?: null | string;
    };
    /**
     * DisruptedLine
     * @description A selector for disrupted sections of a line.
     */
    DisruptedLine: {
      lineRelation: components["schemas"]["LineRelation"];
      /**
       * Sections
       * @description Affected sections [Abschnitte] of line [Linie]. In case list is empty, all sections of line ie the whole line is affected.
       */
      sections: components["schemas"]["LineSection"][];
    };
    /**
     * DisruptionCommunicationOrganisationalUnit
     * @description Organisational unit [Regionalbereich] a disruption communication [Störungskommunikation] may be displayed in.
     */
    DisruptionCommunicationOrganisationalUnit: {
      /**
       * Name
       * @description Name of organisational unit.
       */
      name: string;
      /**
       * Number
       * @description Number of organisational unit, may be empty.
       */
      number?: null | number;
      /**
       * Type
       * @description Organisational unit [Regionalbereich] a disruption communication [Störungskommunikation] may be displayed in.
       *     - DB_REGIO (organisational unit refers to DB Regio terminology)
       *     - DB_STATION_UND_SERVICE (organisational unit refers to DB Station & Service terminology)
       *     - DB_NETZ (organisational unit refers to DB Netz terminology)
       */
      type: string;
    };
    /**
     * DisruptionScenario
     * @description The disruption scenario [Störungsbild] describes what is disrupted and when.
     *
     *     This is used to mark parts of the schedule as unavailable and is applied on top of
     *     all disruption communications from the `RIS::Disruptions` API and realtime schedule
     *     data.
     *
     *     The disruption scenario is applied to the schedule (including modifications by
     *     `RIS::Disruptions` and realtime data) as follows: For each journey run with line `L`
     *     and calls `C[1], ..., C[N]`, the lowest call index `1 <= i < N` such that the time
     *     interval of departure from `C[i]` to arrival at `C[i + 1]` intersects any disruption
     *     for line `L` (taking line sections into account) is determined. If no such index
     *     exists, the journey run is not modified. Otherwise, all calls `C[j]` with `i < j <=
     *     N` are cancelled.
     *
     *     This rule is subject to change in the future. Calls might for example be delayed
     *     instead of cancelled or only cancelled if the delay induced by the disruptions
     *     exceeds a threshold.
     */
    DisruptionScenario: {
      /**
       * Linedisruptions
       * @description List of disrupted line sections at certain time intervals.
       *
       *     The disruption scenario is formed as the union of all array items.
       */
      lineDisruptions: components["schemas"]["LineDisruptions"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * IntervalHeadway
     * @description Individual intervals and its corresponding headway
     */
    IntervalHeadway: {
      /**
       * Headway
       * @description Time between individual connections.
       */
      headway?: null | number;
      /**
       * Interval
       * @description Optional intervals in OSM opening hours format where the alternative is available.
       *
       *     Only the weekday and time features of the 'opening hours' specification is used.
       */
      interval?: null | string;
    };
    /**
     * LineDisruptions
     * @description A selector for disrupted sections of lines at certain time intervals.
     *
     *     The disruption is formed as the union of the cartesian product of all time intervals
     *     and line sections.
     */
    LineDisruptions: {
      /**
       * Disruptedlines
       * @description Line sections that are disrupted in all the given time intervals.
       */
      disruptedLines: components["schemas"]["DisruptedLine"][];
      /**
       * Timeintervals
       * @description Time intervals in an arbitrary order, the intervals may overlap.
       */
      timeIntervals: components["schemas"]["RequestTimeInterval"][];
    };
    /**
     * LineRelation
     * @description Unique identification of a line [Linie] by its line relation [Linienrelation].
     */
    LineRelation: {
      /**
       * Administrationid
       * @description Unique id of the administration [Verwaltung] that operates the line.
       */
      administrationID: string;
      /**
       * Category
       * @description Code of the transport [Fahrtgattung], for city trains for instance 'S'. Must not necessarly be set.
       */
      category?: null | string;
      /**
       * Line
       * @description Line of the transport [Linie].
       */
      line: string;
    };
    /**
     * LineSection
     * @description Unique identification of a line section [Linien-Abschnitt].
     */
    LineSection: {
      /**
       * Fromevanumber
       * @description Affect from stop-place [Haltestelle].
       */
      fromEvaNumber: string;
      /**
       * Singledirection
       * @description Indicates whether line [Linie] is affected only in single direction. Default ist false, meaning that line is affected between from stop-place [Haltestelle] and to stop-place ie in both directions.
       */
      singleDirection?: boolean | null;
      /**
       * Toevanumber
       * @description Affect to stop-place [Haltestelle].
       */
      toEvaNumber: string;
    };
    /**
     * ReplacementTransport
     * @description Replacement transport [Ersatzverkehr] information for a particular disruption-communication [Störungskommunikation].
     */
    ReplacementTransport: {
      /**
       * Begin
       * @description Begin of replacement transport as fully qualified date fully-qualified-date (ISO-8601 with time-zone or offset), must not necessary be the begin of a disruption-communication. May be empty.
       */
      begin?: null | string;
      /**
       * End
       * @description End of replacement transport as fully qualified date fully-qualified-date (ISO-8601 with time-zone or offset), must not necessary be the end of a disruption-communication. May be empty.
       */
      end?: null | string;
      line?: components["schemas"]["LineRelation"] | null;
      /**
       * Type
       * @description Type of replacement transport [Verkehrsart]. Possible values are:
       *     - HIGH_SPEED_TRAIN (High speed train [Hochgeschwindigkeitszug] like ICE or TGV etc.)
       *     - INTERCITY_TRAIN (Inter city train [Intercityzug])
       *     - INTER_REGIONAL_TRAIN (Inter regional train [Interregiozug])
       *     - REGIONAL_TRAIN (Regional train [Regionalzug])
       *     - CITY_TRAIN (City train [S-Bahn])
       *     - SUBWAY (Subway [U-Bahn])
       *     - TRAM (Tram [Strassenbahn])
       *     - BUS (Bus [Bus])
       *     - FERRY (Ferry [Faehre])
       *     - SHUTTLE (Shuttle [Ruftaxi])
       *     - FLIGHT (Flight [Flug])
       *     - UNKNOWN (Unknown)
       */
      type: string;
    };
    /**
     * RequestTimeInterval
     * @description A time interval.
     */
    RequestTimeInterval: {
      /**
       * Begin
       * Format: date-time
       * @description Begin of the time interval.
       */
      begin: string;
      /**
       * End
       * Format: date-time
       * @description End of the time interval.
       */
      end: string;
      /**
       * Intervals
       * @description Optional intervals within [begin, end) in OSM opening hours format.
       *
       *     Note: Only the weekday and time features of the 'opening hours' specification
       *     (https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours) are supported.
       */
      intervals?: null | string;
    };
    /**
     * ResponseStatus
     * @enum {string}
     */
    ResponseStatus:
      | "FOUND_ALTERNATIVES"
      | "FOUND_NOTHING"
      | "NO_ALTERNATIVES_POSSIBLE";
    /** SectionsToCover */
    SectionsToCover: {
      /**
       * Sections
       * @description Continuous list of sections to cover.
       *
       *     Gaps between sections are interpreted as irrelevant in reality (belonging to the
       *     same station) and should be avoided in the input.
       */
      sections: components["schemas"]["LineSection"][];
      /**
       * Singledirection
       * @description Whether the section to cover is only for a single direction or both directions.
       *
       *     If all sections in `sections` have the same `single_direction` value, this value
       *     is used as fallback if `single_direction` is not set. If there is a mix of values an
       *     error is raised. Defaults to `False` if not specified anywhere.
       */
      singleDirection?: boolean | null;
    };
    /**
     * StopPlaceEmbedded
     * @description Comprehensive stop-place [Haltestelle] information.
     */
    StopPlaceEmbedded: {
      /**
       * Evanumber
       * @description Eva number of stop-place [Haltestelle].
       */
      evaNumber: string;
      /**
       * Name
       * @description Name for stop-place [Haltestelle] in fixed language 'DE'.
       */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (number | string)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}
export type $defs = Record<string, never>;
export interface operations {
  alternatives_v1_alternatives_post: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlternativeRoutesRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AlternativeRoutesResponse"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  by_disruption_communication_id_v1_alternatives_by_disruption_communication_id__disruption_communication_id__get: {
    parameters: {
      cookie?: never;
      header?: never;
      path: {
        disruption_communication_id: string;
      };
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AlternativeRoutesResponse"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
  disruptions_metadata_v1_disruptions_metadata_get: {
    parameters: {
      cookie?: never;
      header?: never;
      path?: never;
      query?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: {
              [key: string]: unknown;
            };
          };
        };
        headers: {
          [name: string]: unknown;
        };
      };
    };
  };
}
